import type { Metadata } from "next";
import { Inter, Lato } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import Header from "@/components/Header";
import { Toaster } from "sonner";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const inter = Inter({ subsets: ["latin"] });
const lato = Lato({ subsets: ["latin"], weight: ["100", "300", "400", "700", "900"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Providers>
                <body className={`bg-neutral-800 text-white ${lato.className}`}>
                    <div className=" grid min-h-screen place-items-center grid-cols-1 grid-rows-[auto_1fr] ">
                        <Header />
                        <main className="h-full w-full grid grid-cols-1 py-6 container mx-auto max-sm:px-2">
                            {children}
                        </main>
                    </div>
                    <Toaster richColors position="top-center" />
                    <ReactQueryDevtools initialIsOpen={false} position="bottom" />
                </body>
            </Providers>
        </html>
    );
}
